[package]
name = "commenter"
version = "0.1.0"
authors = ["Adam Bergmark <adam@bergmark.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.5.4"
